### ISSUE TITLE
Draw Card resolutions draws multiple per player

### ISSUE THREAD

**Issue by TheMidnightRose** [stiffmeds/Obeliskial-Options#4]
Any time it triggers conflict resolution, instead of one card per hero, it draws one card per player for each hero. This can happen on draw resolutions as well though I don't have a screenshot of that as it doesn't always happen.

![image](https://github.com/stiffmeds/Obeliskial-Options/assets/32805898/f586ca9d-dcc2-4b95-ba0f-1a095a6aa926)

**Comment by stiffmeds** [comment]
Thanks for the bug report! I've fixed this in commit [ea19b1d](https://github.com/stiffmeds/Obeliskial-Options/commit/ea19b1da81087714fffd49cffe5becae90c1f4ca) (basically: it wasn't checking who the person able to choose was, so the conflict resolution was activating for everyone in the game!), so it'll be fixed in the next release of OO (maybe a week).
